### ISSUE TITLE
add max players allowed to join per second

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#325]
- make sure 
  - per IP probably (so someone doesn't just spam join to prevent other players joining)
  - also per user (one user should not be able to spam join)

basically we just don't want to send SOOOOOO much data that we bypass io uring ring and get invalid data.
There is a lot of data when a player joins.

Open to other ideas on how to solve this problem as well.

**Comment by TestingPlant** [comment]
Regarding per user, we should disconnect the old player if the same user joins again, and probably add a small rate limit (maybe one login every 5 seconds).

I don't think we should do per IP rate limits because many people could be connecting through the same VPN. Also IPv6 makes this more complicated because ISPs give a whole /64 block of IPs which is 2^64 IPs. Different ISPs give a slightly bigger/smaller block size so assuming that everyone has a /64 block might block other people or not be effective in blocking a single person.

**Comment by andrewgazelka** [comment]
not sure what we can really do about this. probs best idea is to use cloudflare or similar.
