### ISSUE TITLE
fix tracy & security

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#394]
security issue probably if it is always on and accessible by anyone! not sure if we need to just add an IP firewall or if we can do something on the rust side.

**Comment by BGR360** [comment]
Not sure if this is an acceptable solution, but you could bind the Tracy listener socket directly to the loopback interface (rather than to all interfaces, which is the default), and then it would only be accessible from the server machine. And if you need to access it remotely, you could create a port forward through ssh I believe.

Just curious, what security issue do you suppose exists from people viewing Tracy data? Perhaps it's obvious to somebody more familiar with Tracy, but I'm not that somebody :)

**Comment by andrewgazelka** [comment]
> Not sure if this is an acceptable solution, but you could bind the Tracy listener socket directly to the loopback interface (rather than to all interfaces, which is the default), and then it would only be accessible from the server machine. And if you need to access it remotely, you could create a port forward through ssh I believe.

ah that could potentially work well. also possible we could add a config that has conservative default options but allows for binding to whatever makes sense.

> Just curious, what security issue do you suppose exists from people viewing Tracy data? Perhaps it's obvious to somebody more familiar with Tracy, but I'm not that somebody :)

more just trying to go for attack surface reduction. if there is a lot of tracing data that is a lot of data the server will have to push. I could see people potentially doing a DoS attack by getting 10/100 clients constantly listening for events.

**Comment by andrewgazelka** [comment]
tracy is disabled for now
