### ISSUE TITLE
Arrow Falling Through Blocks Issue: Discrepancy Between Server and Client Collision Detection

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#449]
the server figures out the correct block collision point but the client still sees the arrow falling through blocks when shooting straight up and letting the arrow fall down

**Comment by andrewgazelka** [comment]
<img width="2168" alt="Google Chrome 2024-06-02 18 22 41" src="https://github.com/andrewgazelka/hyperion/assets/7644264/d4ba761e-80f6-4829-8f07-0365384acc93">

I've noticed this also happens when the arrow isn't being fired straight up or down. When I'm firing it at the bridge, sometimes it can phase through blocks if I shoot it at the edge. At least visually, it looks like this.

**Comment by TestingPlant** [comment]
I've been debugging this for a while but I can't seem to find a solution. I'm going to unassign myself from this so I can work on other areas of Hyperion.

For anyone who wants to take a look at this, I'd suggest using Pakkit to compare Hyperion with a vanilla 1.20.1 Minecraft server. For Pakkit to work, you'll need to comment out code which sends `EntityEquipmentUpdateS2c` packets in Hyperion. I'm not sure if this is an issue in Hyperion or in Pakkit, so I haven't created an issue for it yet. Here's a few notes:
- This issue still occurs with other entities like boats, so this isn't an issue about how Hyperion doesn't currently calculate arrow rotation.
- For debugging, an arrow with a specific velocity and position can be spawned in vanilla Minecraft using `/summon minecraft:arrow 0 -15 0 {Motion:[0.0, 3.0, 0.0]}`. These values need to be hard-coded in `release_item.rs` in Hyperion.
- Vanilla Minecraft seems to calculate drag and/or gravity differently than Hyperion. This could possibly be an issue because the Minecraft client seems to simulate entity physics to some extent, but to avoid desync as blocks are placed and broken, we shouldn't rely solely on the client's entity physics and we should continue sending entity position packets.
- Vanilla Minecraft seems to not use 1/8000th of a block as units for velocity; the position change packets and the velocity don't seem to line up.
- This likely isn't an issue with `rounding_error` in `sync_entity_position.rs`; when removed, the arrow still goes further than what a rounding error could've caused.

**Comment by andrewgazelka** [comment]
closing this as old and not relevant anymore as does not exist post recode
