### ISSUE TITLE
Localize broadcasting / packet sending

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#459]
There's a lot that needs to be figured out regarding how we're going to manage local broadcasts. We already have the local broadcast packet in the proxy, but how would we handle events that happen on the edge of that local region? For instance, a player should be marked as despawning (or something like that) once they cross the radius of visibility. I think we will need to track some amount of state on the proxy.

Current protocol:

https://github.com/andrewgazelka/hyperion-proto/blob/50884bc32a02454d6dcbd5c0811b66d65380f480/src/server_to_proxy.proto#L1-L57

Ideally, we don't want too much spaghetti code.

**Comment by TestingPlant** [comment]
Since the majority of local broadcasts are from entity movement packets, I'll describe my idea for entity movement packets below:

In the proxy, we will want to implement droppable movement packets to support users with slow connections and to reduce the network usage of the proxy. We should structure the entity movement code to support this to avoid a rewrite later and since this would help with despawning far away entities. If we were to drop movement packets with deltas, this would cause the entity's position to be incorrect because future deltas will be based off of the dropped packet's delta. A potential solution to this could be:

On the proxy:
1. Have multiple streams per entity that players can subscribe to. For example, entities might have 5 streams each: one stream with entity movement updates sent every tick, one with updates sent every 2 ticks, one with updates sent every 5 ticks, one with updates sent every 10 ticks, and one with updates sent every 20 ticks. The exact numbers can change later, but this is a good starting point.
2. Each player updates what streams they're subscribing to based on how far they are from that entity and the player's internet speed every 20 ticks. Note that 20 is divisible by each interval above, so this shouldn't cause issues with deltas. This step can also be used to send despawn packets to entities that are far away.
3. On each tick, iterate through each stream, generate the packet, and send it to subscribers.

On the server:
On each tick, send entity movements to each proxy on each tick.
