### ISSUE TITLE
[TRACKING] close attack vectors

### ISSUE THREAD

**Issue by andrewgazelka** [andrewgazelka/hyperion#479]
this is a tracking issue for all attack vectors

- #326 
- #192

**Comment by BGR360** [comment]
Suggested additions:
- prevent TCP connection count DoS attacks
  - naive idea: limit 1 TCP connection per IP address (does not protect against DDoS or spoofed source IPs)
  - another idea: throttle the total number of newly accepted TCP connections per second
  - another idea: aggressively prune idle, seemingly-idle, or otherwise suspicious connections
  - or perhaps decide that this problem is too complex to solve well enough in Hyperion and recommend the use of services like https://tcpshield.com/
- ensure use of DoS-resistant hash functions in all HashMaps, or audit usages of non-DoS-resistant hash functions and prove that they are impossible or extremely unlikely to be exploited

**Comment by andrewgazelka** [comment]
> Suggested additions:
> 
> * prevent TCP connection count DoS attacks
>   
>   * naive idea: limit 1 TCP connection per IP address (does not protect against DDoS or spoofed source IPs)
>   * another idea: throttle the total number of newly accepted TCP connections per second
>   * another idea: aggressively prune idle, seemingly-idle, or otherwise suspicious connections
>   * or perhaps decide that this problem is too complex to solve well enough in Hyperion and recommend the use of services like https://tcpshield.com/
> * ensure use of DoS-resistant hash functions in all HashMaps, or audit usages of non-DoS-resistant hash functions and prove that they are impossible or extremely unlikely to be exploited

Yea we are probably going to be behind something like TCP Shield (better safe than sorry) at least to start out with. There are still probably plenty of attack vectors though.

**Comment by andrewgazelka** [comment]
closing this for now. i don't think we need a trackign issue
